name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      KERNEL_TYPE:
        description: 'Kernel Type'
        required: true
        default: 'Default'
        type: choice
        options:
        - Default
        - KernelSU-Next + SUSFS
      KERNEL_SOURCE:
        description: 'Motorola Kernel Source'
        required: true
        default: 'https://github.com/MotorolaMobilityLLC/kernel-mtk.git'
      KERNEL_BRANCH:
        description: 'Kernel Branch'
        required: true
        default: 'MMI-U4UI34.8-22-7'
        type: choice
        options:
        - MMI-U4UI34.8-22-7
        - MMI-V1UI35H.11-39-16
        - MMI-V1UIS35H.11-39-16-2
        - MMI-V1UIS35H.11-39-16-5
        - MMI-V1UIS35H.11-39-28-5

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
              
    - name: Update and Install Packages
      run: |
        sudo apt update && sudo apt install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo

    - name: Sync Kernel Source
      run: |
         git clone ${{ inputs.KERNEL_SOURCE}} -b ${{ inputs.KERNEL_BRANCH}} kernel_sync

    - name: Add KernelSU-Next
      if: ${{ inputs.KERNEL_TYPE == 'KernelSU-Next + SUSFS' }}
      run: |
         cd kernel_sync
         curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -

    - name: Add SUSFS
      if: ${{ inputs.KERNEL_TYPE == 'KernelSU-Next + SUSFS' }}
      run: |
         cd ..
         git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
         cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch kernel_sync/KernelSU/
         cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-gki-android14-6.1.patch kernel_sync/
         cp susfs4ksu/kernel_patches/fs/* kernel_sync/fs
         cp susfs4ksu/kernel_patches/include/linux/* kernel_sync/include/linux
         cd kernel_sync/KernelSU && patch -p1 < 10_enable_susfs_for_ksu.patch
         patch -p1 < 50_add_susfs_in_kernel.patch
         
         
